#!/usr/bin/env bash

switch_to() {
    if [[ -z $TMUX ]]; then
        tmux attach-session -t "$1"
    else
        tmux switch-client -t "$1"
    fi
}

has_session() {
    tmux list-sessions | grep -q "^$1:"
}

selected_name="opencode_$(basename "$PWD")"
if [[ $1 == "peek" ]]; then
    if has_session "$selected_name"; then
        tmux split-window -h "tmux capture-pane -t $selected_name:1 -p && sleep 1000"
    else
        echo "no opencode session found"
    fi
    exit 0
fi

tmux_running=$(pgrep tmux)
if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
    echo "tmux is not running, please use tmux-sessionizer to start a tmux session"
    exit 1
fi

if ! has_session "$selected_name"; then
    tmux new-session -ds "$selected_name" -c "$PWD" long_running_program
fi

switch_to "$selected_name"


